### PR TITLE
fix for pagination in LoadPlaylistDeadline

### PR DESCRIPTION
**Pull request by korchasa**
`index` param is a offset, not a page number

### CODE REVIEW

**Comment by lithdew** [comment]
Looking at it now to double-check! Thanks for the PR :smile:.

**Comment by lithdew** [comment]
I double-checked it with playlist ID `PLWwAypAcFRgKAIIFqBr9oy-ZYZnixa_Fj`, where each page appears to be 200 items each.

I think rather than assume each page has at most 200 items, it would be better to just rename the parameter to `offset` instead and developers using the API could set the offset accordingly.

What do you think?

**Comment by korchasa** [comment]
You are right! It will be more predictable and flexible.

**Comment by lithdew** [comment]
> You are right! It will be more predictable and flexible.

I pushed a commit to reflect the change from `page` to `offset`.

Let me know if you encounter anything else :smile:.

**Comment by korchasa** [comment]
Thanks!

**Pull request closed without merging**
